### ISSUE TITLE
throwing Error when installing 

### ISSUE THREAD

**Issue by SaiMounikaRao** [obermillerk/win-wifi#5]
if not defined npm_config_node_gyp (node "C:\Users\dev\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --msvs_version=2015 ) else (node "" rebuild --msvs_version=2015 )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.Cpp.Platform.targets(64,5): error MSB8020: The build t
ools for v140 (Platform Toolset = 'v140') cannot be found. To build using the v140 build tools, please install v140 bui
ld tools. Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-cli
ck the solution, and then selecting "Upgrade Solution...". [F:\mounika\FULLClient-Electron\node_modules\win-wifi\node_m
odules\windows.devices.enumeration\build\binding.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack at ChildProcess.onExit (C:\Users\dev\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack at emitTwo (events.js:106:13)
gyp ERR! stack at ChildProcess.emit (events.js:191:7)
gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\dev\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--msvs_version=2015"
gyp ERR! cwd F:\mounika\FULLClient-Electron\node_modules\win-wifi\node_modules\windows.devices.enumeration
gyp ERR! node -v v6.10.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN AnyWhereWorks@4.2.0 No description
npm WARN AnyWhereWorks@4.2.0 No repository field.
npm WARN AnyWhereWorks@4.2.0 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! windows.devices.enumeration@0.1.0 install: `node-gyp rebuild --msvs_version=2015`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the windows.devices.enumeration@0.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\dev\AppData\Roaming\npm-cache\_logs\2017-10-26T12_28_01_116Z-debug.log

**Comment by obermillerk** [comment]
Hi,
Apologies I haven't gotten around to writing docs yet, but you need to have windows-build-tools installed before this library will install.  From an admin command line (needs admin to write to program files): `npm install -g windows-build-tools`  Let me know if this fixes it!
